### PR TITLE
base64 to_file support

### PR DESCRIPTION
**Pull request by MrZilinXiao**
I found that there is no base64 to_file support in python-wechaty-puppet, leading to examples here won't trigger the image saving action since `img = await msg.to_file_box()` makes `img` a base64-filebox.

image

https://github.com/wechaty/python-wechaty-getting-started/blob/1cb320513536c74178023be2bf511bd233628990/examples/advanced/message-file-bot.py#L48

### CODE REVIEW

**Comment by wj-Mcat** [comment]
It's great to see that you have your contribution to `python-wechaty`. This support is welcome.

**Comment by wj-Mcat** [comment]
You should update the version in `VERSION` file to deploy the `wechaty-puppet-hostie` to pypi repo. @MrZilinXiao

**Comment by MrZilinXiao** [comment]
> You should update the version in `VERSION` file to deploy the `wechaty-puppet-hostie` to pypi repo. @MrZilinXiao Waiting for your next bump of version.

Like pumping 0.0.15 to 0.0.16 like this? 
Sorry for the inconvenience since it's my first time to submit PR to python-wechaty puppet.

**Comment by wj-Mcat** [comment]
@lijiarui the student @MrZilinXiao has become our wechaty contributor, please invite him.

**Comment by huan** [comment]
@wj-Mcat Awesome, and welcome @MrZilinXiao !

**Pull request merged**
